apiVersion: batch/v1
kind: CronJob
metadata:
  name: demosvc
spec:
  # schedule: "*/20 8-19 * * 1-5"
  schedule: '0 * * * *'
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: demosvc
        spec:
          containers:
          - name: demosvc
            image: konicsdev/demo-svc
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure