apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  labels:
    name: ingress-srv
spec:
  rules:
  - host: posts.com
    http:
      paths:
      - pathType: Prefix
        path: "/post"
        backend:
          service:
            name: post-clusterip-srv
            port: 
              number: 3002
 